name: calendar_old
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"  # Null-Safety対応以前の古いSDK
  #sdk: ">=2.12.0 <3.0.0"  # Null-Safety対応の最新SDK

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  cloud_firestore: ^2.2.2  # Cloud Firestore APIを使用するためのFlutterプラグイン
  device_info: ^2.0.2  # 2021年末に廃止される。Flutterアプリケーション内で、現在のデバイス情報を取得
  # device_info_plus: ^1.0.1  # Flutterアプリケーション内で、現在のデバイス情報を取得
  firebase_analytics: ^8.1.2  #　firebase_analytics APIを使用するためのFlutterプラグイン
  firebase_auth: ^1.4.1  #　firebase_auth APIを使用するためのFlutterプラグイン
  firebase_core: ^1.3.0  #　複数のFirebaseアプリへの接続を可能にするFirebase Core APIを使用する
  firebase_crashlytics: ^2.0.6  #　firebase_crashlytics APIを使用するためのFlutterプラグイン
  firebase_helpers: ^0.4.0  #　様々なGoogle Firebase関連サービスのヘルパーを提供するパッケージ
  firebase_messaging: ^10.0.2  #　Firebase Cloud Messaging APIを使用するためのFlutterプラグイン
  firebase_remote_config: ^0.10.0+2  #　Firebase Remote Config APIを使用するためのFlutterプラグイン
  firebase_storage: ^8.1.3  #　Firebase Cloud Storage APIを使用するためのFlutterプラグイン
  flutter_auth_buttons: ^0.9.0  # このプラグインは廃止された
  flutter_form_builder: ^6.0.1  # データ収集フォームの作成に役立つ
  flutter_riverpod: ^0.14.0+3  # 状態管理ライブラリ
  flutter_svg: ^0.22.0  # SVG（および一部のAndroid VectorDrawable（XML））ファイルを描画
  flutter_swiper: ^1.1.6  # 複数のレイアウトと無限ループを備えた、flutter用の最高のスワイパー
  google_fonts: ^2.1.0  # fonts.google.comにある977種類のフォント（およびそのバリエーション）を簡単に使用
  google_sign_in: ^5.0.4  # Google Sign InのためのFlutterプラグイン
  image_cropper: ^1.4.0  # 画像のトリミングをサポート
  image_picker:  ^0.8.0+3  # 画像ライブラリから画像を選択し、カメラで新しい写真を撮る
  intl: ^0.17.0  # メッセージの翻訳、複数形と性別、日付/数字のフォーマットと解析、双方向テキストなど、国際化とローカライゼーションの機能を提供
  package_info: ^2.0.2  # 2021年末に廃止される。アプリケーションパッケージに関する情報をクエリするためのAPIを提供
  #  package_info_plus: ^1.0.2  # アプリケーションパッケージに関する情報をクエリするためのAPIを提供
  table_calendar: ^3.0.0  # Flutter用の高度にカスタマイズ可能な機能満載のカレンダー
  change_app_package_name: ^1.0.0  # 1つのコマンドでアプリパッケージ名を変更
  #  flutter_automation: ^1.4.0  # プロジェクトのさまざまな側面を自動化するのに役立つさまざまな自動化スクリプトが含む
  #  intl_translation: ^0.17.0  # 翻訳されたメッセージからのメッ セージ抽出とコード生成を提供

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_intl:
  enabled: true
